apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bsp-ctlg-backend-mod-extensions
  namespace: rhdh
  title: "Catalog Backend Module Extensions"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/extensions
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/extensions
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-catalog-backend-module-extensions"
  # Tag: 1.11--0.17.1, Build date: 2026-07-06T11:29:21Z
  dynamicArtifact: "oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-catalog-backend-module-extensions@sha256:f9858eaecd059b882c520f5cc08b3d5bdab181e5cd8ba79281543bedf78aa792"
  version: 0.17.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.4
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - extensions
  appConfigExamples:
    - title: Optional extensions directory
      content:
        extensions:
          directory: ${RHDH_EXTENSIONS_DIRECTORY}
